spring.datasource.url=jdbc:postgresql://schedule-db:5432/schedule_db
spring.datasource.username=postgres
spring.datasource.password=12345678

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
# Distributed Tracing with Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
# Eureka

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

app.cors.allowed-origins=http://localhost:8080,http://localhost:3000,http://localhost:4200
springdoc.swagger-ui.servers=http://localhost:8080/schedule,http://localhost:9191

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.movieServiceClient.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.movieServiceClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.movieServiceClient.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.movieServiceClient.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.movieServiceClient.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.movieServiceClient.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.circuitbreaker.instances.ticketServiceClient.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.ticketServiceClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ticketServiceClient.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.ticketServiceClient.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.ticketServiceClient.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.ticketServiceClient.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.retry.instances.movieServiceClient.max-attempts=3
resilience4j.retry.instances.movieServiceClient.wait-duration=2s

resilience4j.retry.instances.ticketServiceClient.max-attempts=3
resilience4j.retry.instances.ticketServiceClient.wait-duration=2s

# Actuator Health Indicators
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
