spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=postgres

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

security.jwt.secret=my-secret-key
security.jwt.expiration=86400000

