spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=12345678

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate

# Distributed Tracing with Zipkin
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans


# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
