spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=12345678

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false


# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
